name: PortfolioSite-CD   # ì›Œí¬í”Œë¡œ ì´ë¦„

on:
  push:
    branches:
      - main

jobs:
  backend-deploy:        # job ì´ë¦„
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“‚ ì½”ë“œ ê°€ì ¸ì˜¤ê¸°
        uses: actions/checkout@v3

      - name: â˜• JDK ì„¸íŒ…
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ðŸ—ï¸ ë¹Œë“œ
        run: ./gradlew clean build -x test

      - name: ðŸš€ ì„œë²„ì— ì—…ë¡œë“œ
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/libs/*.jar"
          target: ${{ secrets.APP_PATH }}

      - name: ðŸ”„ ì„œë²„ ì‹¤í–‰
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.APP_PATH }}
            mv build/libs/*.jar app.jar
            fuser -k 8080/tcp || true
            nohup java -jar app.jar --spring.config.location=${{ secrets.APP_PATH }}/application.properties > app.log 2>&1 &